Importação das bibliotecas e/ou módulos (packages ou pacotes) necessários.

In [2]:
# Importar as bibliotecas necessárias
import pandas as pd
# https://pandas.pydata.org/

# Conversão de dados categóricos em numéricos
from sklearn.preprocessing import LabelEncoder
# https://scikit-learn.org/stable/modules/preprocessing.html

# Algoritmos de classificação
# KNN (K-Nearest Neighbors)
from sklearn.neighbors import KNeighborsClassifier
# https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html

# Decision Tree
from sklearn.tree import DecisionTreeClassifier
# https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html

# Seleção de dados de treino e teste
from sklearn.model_selection import train_test_split
# https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html

# Obtenção da acurácia do modelo
from sklearn.metrics import accuracy_score
# https://scikit-learn.org/stable/modules/generated/sklearn.metrics.accuracy_score.html

Importação dos dados

https://www.kaggle.com/datasets/shivam2503/diamonds

In [4]:
# Criar um Pandas Data Frame a partir do arquivo de dados csv
dados = pd.read_csv('diamonds.csv')
dados

Unnamed: 0  carat        cut color clarity  depth  table  price     x  \
0               1   0.23      Ideal     E     SI2   61.5   55.0    326  3.95   
1               2   0.21    Premium     E     SI1   59.8   61.0    326  3.89   
2               3   0.23       Good     E     VS1   56.9   65.0    327  4.05   
3               4   0.29    Premium     I     VS2   62.4   58.0    334  4.20   
4               5   0.31       Good     J     SI2   63.3   58.0    335  4.34   
...           ...    ...        ...   ...     ...    ...    ...    ...   ...   
53935       53936   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75   
53936       53937   0.72       Good     D     SI1   63.1   55.0   2757  5.69   
53937       53938   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66   
53938       53939   0.86    Premium     H     SI2   61.0   58.0   2757  6.15   
53939       53940   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83   

          y     z  
0      3.98  2.43  
1      3.84  2.31  
2      4.07  2.31  
3      4.23  2.63  
4      4.35  2.75  
...     ...   ...  
53935  5.76  3.50  
53936  5.75  3.61  
53937  5.68  3.56  
53938  6.12  3.74  
53939  5.87  3.64  

[53940 rows x 11 columns]

Análise Exploratória

In [5]:
# Quantos registros (linhas) e quantos atributos (colunas) tem o Data Frame?
dados.shape
print(f'O conjunto de dados tem {dados.shape[0]} linhas e {dados.shape[1]} colunas.')

O conjunto de dados tem 53940 linhas e 11 colunas.


In [6]:
# Visualizar as primeiras linhas
dados.head()

Unnamed: 0  carat      cut color clarity  depth  table  price     x     y  \
0           1   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98   
1           2   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84   
2           3   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07   
3           4   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23   
4           5   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35   

      z  
0  2.43  
1  2.31  
2  2.31  
3  2.63  
4  2.75

In [7]:
# Visualizar as últimas linhas
dados.tail()

Unnamed: 0  carat        cut color clarity  depth  table  price     x  \
53935       53936   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75   
53936       53937   0.72       Good     D     SI1   63.1   55.0   2757  5.69   
53937       53938   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66   
53938       53939   0.86    Premium     H     SI2   61.0   58.0   2757  6.15   
53939       53940   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83   

          y     z  
53935  5.76  3.50  
53936  5.75  3.61  
53937  5.68  3.56  
53938  6.12  3.74  
53939  5.87  3.64

In [8]:
# Nomes das colunas
dados.columns

Index(['Unnamed: 0', 'carat', 'cut', 'color', 'clarity', 'depth', 'table',
       'price', 'x', 'y', 'z'],
      dtype='object')

In [9]:
# Informações do formato de dados das colunas
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  53940 non-null  int64  
 1   carat       53940 non-null  float64
 2   cut         53940 non-null  object 
 3   color       53940 non-null  object 
 4   clarity     53940 non-null  object 
 5   depth       53940 non-null  float64
 6   table       53940 non-null  float64
 7   price       53940 non-null  int64  
 8   x           53940 non-null  float64
 9   y           53940 non-null  float64
 10  z           53940 non-null  float64
dtypes: float64(6), int64(2), object(3)
memory usage: 4.5+ MB


In [10]:
# Estatísticas descritivas das colunas numéricas
dados.describe()

Unnamed: 0         carat         depth         table         price  \
count  53940.000000  53940.000000  53940.000000  53940.000000  53940.000000   
mean   26970.500000      0.797940     61.749405     57.457184   3932.799722   
std    15571.281097      0.474011      1.432621      2.234491   3989.439738   
min        1.000000      0.200000     43.000000     43.000000    326.000000   
25%    13485.750000      0.400000     61.000000     56.000000    950.000000   
50%    26970.500000      0.700000     61.800000     57.000000   2401.000000   
75%    40455.250000      1.040000     62.500000     59.000000   5324.250000   
max    53940.000000      5.010000     79.000000     95.000000  18823.000000   

                  x             y             z  
count  53940.000000  53940.000000  53940.000000  
mean       5.731157      5.734526      3.538734  
std        1.121761      1.142135      0.705699  
min        0.000000      0.000000      0.000000  
25%        4.710000      4.720000      2.910000  
50%        5.700000      5.710000      3.530000  
75%        6.540000      6.540000      4.040000  
max       10.740000     58.900000     31.800000

In [11]:
# Estatísticas descritivas das colunas não numéricas
dados.describe(include='object')

cut  color clarity
count   53940  53940   53940
unique      5      7       8
top     Ideal      G     SI1
freq    21551  11292   13065

In [12]:
# Seleção dos dados de uma coluna (formato Series)
preco_series = dados['price']
preco_series

0         326
1         326
2         327
3         334
4         335
         ... 
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64

In [13]:
# Seleção dos dados de uma coluna (formato Data Frame)
preco_df = dados[['price']]
preco_df

price
0        326
1        326
2        327
3        334
4        335
...      ...
53935   2757
53936   2757
53937   2757
53938   2757
53939   2757

[53940 rows x 1 columns]

In [14]:
type(preco_df)

pandas.core.frame.DataFrame

In [15]:
# Cálculo de média aritmética dos valores de uma coluna
media_aritm = dados['price'].mean().round(4)
media_aritm

3932.7997

In [16]:
# Cálculo de mediana dos valores de uma coluna
mediana = dados['price'].median().round(4)
mediana

2401.0

In [17]:
# Cálculo do desvio padrão dos valores de uma coluna
desvio_padrao = dados['price'].std().round(4)
desvio_padrao

3989.4397

Pré Processamento

In [18]:
dados.head()

Unnamed: 0  carat      cut color clarity  depth  table  price     x     y  \
0           1   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98   
1           2   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84   
2           3   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07   
3           4   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23   
4           5   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35   

      z  
0  2.43  
1  2.31  
2  2.31  
3  2.63  
4  2.75

In [19]:
# Exclusão de uma coluna usando o método .drop
# axis = 0 ----> linha
# axis = 1 ----> coluna
dados = dados.drop('Unnamed: 0', axis=1)
dados

carat        cut color clarity  depth  table  price     x     y     z
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]

In [20]:
# Conversão dos dados de uma coluna em um Array Numpy (Vetor)
vetor_numpy = dados['price'].values
vetor_numpy

array([ 326,  326,  327, ..., 2757, 2757, 2757])

In [21]:
# Conversão de uma coluna de valores categóricos para numéricos
# Label Encoding
le = LabelEncoder()

In [22]:
dados['cut'].values

array(['Ideal', 'Premium', 'Good', ..., 'Very Good', 'Premium', 'Ideal'],
      dtype=object)

In [23]:
dados['cut'] = le.fit_transform(dados['cut'])

In [24]:
dados['cut'].values

array([2, 3, 1, ..., 4, 3, 2])

In [25]:
dados.head()

carat  cut color clarity  depth  table  price     x     y     z
0   0.23    2     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21    3     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23    1     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29    3     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31    1     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [26]:
# Separação dos dados de entrada e dados de saída
# X maiúsculo ----> Dados de entrada / Features / Variáveis independentes
# y minúsculo ----> Dados de saída / Target (alvo) / Variável dependente
# dados.iloc[linhas, colunas]
X = dados.iloc[:, 7:] # Todas as linhas e as colunas de 7 a 9.
X.head()

x     y     z
0  3.95  3.98  2.43
1  3.89  3.84  2.31
2  4.05  4.07  2.31
3  4.20  4.23  2.63
4  4.34  4.35  2.75

In [27]:
X.shape

(53940, 3)

In [28]:
X.values

array([[3.95, 3.98, 2.43],
       [3.89, 3.84, 2.31],
       [4.05, 4.07, 2.31],
       ...,
       [5.66, 5.68, 3.56],
       [6.15, 6.12, 3.74],
       [5.83, 5.87, 3.64]])

In [29]:
y = dados['cut'].values
y

array([2, 3, 1, ..., 4, 3, 2])

Separação em dados de treino e dados de teste

A separação de dados em conjuntos de treinamento e teste é uma prática fundamental na construção e avaliação de modelos de aprendizado de máquina. A ideia principal é usar uma parte dos seus dados para treinar o modelo (conjunto de treinamento) e outra parte para avaliar o desempenho do modelo (conjunto de teste). A razão para fazer isso é avaliar a capacidade do modelo de generalizar para dados não vistos, ou seja, dados que não foram usados durante o treinamento.

A função train_test_split é uma maneira conveniente de realizar essa separação. Ela trabalha com números randômicos por duas razões principais:

Garantir Generalização: Quando você treina um modelo, você deseja que ele aprenda padrões presentes nos dados, em vez de simplesmente memorizar os exemplos de treinamento. Para testar a capacidade de generalização do modelo, você deve avaliá-lo em dados que ele nunca viu antes. A aleatoriedade na divisão ajuda a simular essa situação, garantindo que o modelo seja avaliado em dados diferentes dos utilizados no treinamento.

Evitar Viés de Seleção: A aleatoriedade na divisão ajuda a evitar qualquer viés que possa estar presente nos seus dados. Se você não dividir seus dados de forma aleatória, pode haver uma tendência a selecionar exemplos mais fáceis ou mais difíceis para o treinamento ou teste, o que pode prejudicar a validade das avaliações do modelo.



In [35]:
 # https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)
X_train

x     y     z
34477  4.61  4.64  2.86
31585  4.52  4.54  2.81
37728  4.32  4.30  2.67
48766  5.06  5.07  3.14
2198   5.71  5.76  3.58
...     ...   ...   ...
45764  5.43  5.48  3.28
14789  7.05  7.00  4.32
16657  7.10  7.05  4.29
43275  4.27  4.25  2.65
2647   5.96  6.01  3.75

[37758 rows x 3 columns]

In [31]:
X_train.shape

(37758, 3)

X: dados de entrada.

y: dados de saída (rótulos / variável dependente).

test_size: define a proporção dos dados que serão usados como conjunto de teste (geralmente entre 0.2 e 0.3).

random_state: é uma "semente" (SEED) para o gerador de números randômicos. Fornece um valor específico (constante) garante que a divisão seja reprodutível, ou seja, você obterá a mesma divisão sempre que usar o mesmo valor.

Escolha do algoritmo

In [69]:
# Instanciar o modelo
modelo_knn = KNeighborsClassifier(n_neighbors=5)

In [70]:
# Treinar o modelo
modelo_knn.fit(X_train, y_train)

KNeighborsClassifier()

In [71]:
# Realizar as predições
y_predict = modelo_knn.predict(X_test)
y_predict

array([4, 3, 4, ..., 2, 4, 1])

In [72]:
# Calcular a acurácia do modelo
acuracia = 100 * (accuracy_score(y_test, y_predict))
print(f'A acuracia do modelo baseado no algoritmo KNN é de {acuracia :.2f}%')

A acuracia do modelo baseado no algoritmo KNN é de 61.12%


EXERCÍCIO: Treine um outro modelo usando o algoritmo Decision Tree e compare as métricas

In [73]:
modelo_dt = DecisionTreeClassifier()
# modelo_dt

In [74]:
modelo_dt.fit(X_train, y_train)

DecisionTreeClassifier()

In [75]:
y_predict_dt = modelo_dt.predict(X_test)

In [76]:
acuracia_dt = 100 * (accuracy_score(y_test, y_predict_dt))
print(f'A acuracia do modelo baseado no algoritmo KNN é de {acuracia_dt :.2f}%')

A acuracia do modelo baseado no algoritmo KNN é de 55.99%
